### ISSUE TITLE
Add `importPT` option to module config

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue-nuxt-module#11]
Users want to set their own custom presets or ready-made presets in nuxt.config. Due to some limitations (Ref: https://github.com/primefaces/primevue-nuxt-module/issues/6#issuecomment-1772954754), the `importPT` option can be used instead of `options.pt`.

Usage:
```js
// nuxt.config.js
primevue: {
  importPT: { as: <Default_Export_As_String>, from: <Package_Path> },
  ...
}
```
<hr />

Example 1:
```js
// nuxt.config.js
primevue: {
  importPT: { as: 'Tailwind', from: 'primevue/passthrough/tailwind' },
  ...
}
```

Example 2:
```js
// nuxt.config.js
import path from 'path';
...

primevue: {
  importPT: { as: 'CustomTailwind', from: path.resolve(__dirname, './assets/presets/custom.js')}
  ...
}
```

```js
// assets/presets/custom.js

const CustomTailwind = {
    ...
    button: {
        root: 'my-button',
       ...
    },
    ...
}

export default CustomTailwind;
```

**Comment by rogrile** [comment]
Could you provide a working example in nuxt with Tailwind PT? For me this doesn't work for some reason.

**Comment by mertsincan** [comment]
Sorry for the delayed response. Please see;
https://github.com/primefaces/primevue-examples/blob/main/nuxt-unstyled-tailwind/nuxt.config.ts
