### ISSUE TITLE
Error on vercel deployment

### ISSUE THREAD

**Issue by joseehilton147** [primefaces/primevue-nuxt-module#12]
![image](https://github.com/primefaces/primevue-nuxt-module/assets/53986027/c2f91e9f-5935-4844-8e60-6cc75dcfb1ce)

After migrate to nuxt module i got this error, doing the old way (before update), using plugin folder, works correctly

**Comment by mertsincan** [comment]
Hi @joseehilton147, could you please try the following config;
```
// nuxt.config.js
...
primevue: {
    ...
    components: {
        exclude: ['Editor', 'Chart']
    }
}
...
```

**Comment by joseehilton147** [comment]
Hi @mertsincan , sorry for late response, with exclude works correctly, ty

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update!
