### ISSUE TITLE
Error on cloudflare pages deployment

### ISSUE THREAD

**Issue by cristiancosano** [primefaces/primevue-nuxt-module#13]
After migrating from a custom Nuxt plugin to the PrimeVue Nuxt Module, I encountered an error when deploying my application on Cloudflare Pages.

- Nuxt version: 3.8 (I also tried with version 3.7)
- PrimeVue version: 3.38.1
- PrimeVue Nuxt Module version: 0.1.0

In Cloudflare's logs, I received the following error message:

<img width="890" alt="image" src="https://github.com/primefaces/primevue-nuxt-module/assets/55451102/63ebb547-e6a2-4014-8432-a9a667830b10">

The build process was successful, but the error occurred when Cloudflare attempted to deploy the application to its global network.

View the complete Cloudflare log here:
[cloudflare.log](https://github.com/primefaces/primevue-nuxt-module/files/13199227/cloudflare.log)

I'm sure this issue is caused by using the module because it works correctly with the Nuxt plugin, and when I deactivate the module during deployment on Cloudflare, there are no errors. The error only occurs on Cloudflare. If I build the project locally (node preset), I don't receive any errors.

**Comment by mertsincan** [comment]
This is interesting! We don't use any document object. We only register the components like in the nuxt-plugin. I think this is related to cloudflare + nitro. Nuxt-primevue module uses a custom nitro plugin to append the styles of components to html.head. This may have caused the problem. Could you please try to set `cloudflare` or `cloudflare_pages` preset in nuxt.config.js?

```
// nuxt.config.js
...
nitro: {
     preset: 'cloudflare'
}
...
```
Refs;
https://nitro.unjs.io/config#preset
https://nitro.unjs.io/deploy/providers/cloudflare

**Comment by mertsincan** [comment]
Hi,

For now, closed. If there is any update from your side, please reopen it. Thanks a lot for your understanding!

Best Regards,
