### ISSUE TITLE
Nuxt build error realted to rollup

### ISSUE THREAD

**Issue by YoungKamilson** [primefaces/primevue-nuxt-module#16]
Hi, I encountered error when building Nuxt app after I installed nuxt primevue module. It happens on my local machine and vercel's deploy.

--------------------------

**Versions:**

- nuxt: 3.7.4,
- nuxt-primevue: 0.1.0,
- chart.js: 4.4.0,
- node: 18.17.1

--------------------------

**Error message:**

ERROR  Nuxt Build Error: [vite]: Rollup failed to resolve import "quill" from "Q:/WWW/GIT_PROJECTS/termin.ai.portal/node_modules/primevue/editor/editor.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

--------------------------

How to repair it?

**Comment by mertsincan** [comment]
Hi,
For now, please use;
```
primevue: {
   components: {
      exclude: ['Editor', 'Chart']
   }
}
```
Fixed for next version; https://github.com/primefaces/primevue-nuxt-module/issues/17

Best Regards,

**Comment by molul** [comment]
Hi. I'm having this same error ([error] Nuxt Build Error: [vite]: Rollup failed to resolve import "quill" from "/vercel/path0/node_modules/primevue/editor/index.mjs".) when deploying my nuxt app to Vercel.

This is my primevue config in nuxt.config.ts (the workaround mentioned here didn't work):

```
primevue: {
    options: {
      locale: primevueLocaleOptions,
      ripple: false,
      unstyled: true,
      theme: {
        options: {
          cssLayer: {
            name: 'primevue'
          }
        }
      }
    },

    importPT: {
      from: path.resolve(__dirname, './assets/primevuePresets/main/')
    },

    autoImport: false,
    components: {
      include: '*',
      exclude: ['Editor', 'Chart']
    }
  },
```
