### ISSUE TITLE
Exclude `Chart` and `Editor` components by default

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primevue-nuxt-module#17]
Components that use such 3rd party APIs cause a lot of problems for users. So they can be excluded by default.

**Comment by shino47** [comment]
> Am I missing something?

I had the same problem. If you look here: https://github.com/primefaces/primevue-nuxt-module/blob/ea01e017311f4988890c6ce7203b65269cdabfdc/src/module.ts#L40

Editor and Chart are excluded by default, so you need to pass a non falsy value to the exclude property:

```javascript
primevue: {
  components: {
    include: '*',
    exclude: [], // here
  },
},
```

If you do `include: ["Editor"]`, only the Editor componet will be auto loaded, so you need to use the `*` wildcard to load everything.

**Comment by RustyRaptor** [comment]
This very badly needs to be in the documentation lol.

**Comment by reitowo** [comment]
Faced this issue again. Can you change to: If include `Editor` explicitly, ignore what exclude set?
