### ISSUE TITLE
Add cssLayerOrder works on dev, but can not work on prod

### ISSUE THREAD

**Issue by minhanbkdn** [primefaces/primevue-nuxt-module#20]
I'm working on a Nuxt 3 project using Tailwind and PrimeVue.
It works perfectly for me when I use setting `cssLayerOrder: 'primevue, tailwind-base, tailwind-utilities'`, but that config just works on dev (`yarn dev`) only (image 1).
When I deploy it into the server (`yarn build && node .output/server/index.mjs`) the CSS order not match with the config (image 2)

- image 1 (match with the config, works in dev):
![image](https://github.com/primefaces/primevue-nuxt-module/assets/36067662/16a48907-5c83-4d26-ace3-ed7b1759ffaf)
- image 2 (not match with the config, not works in prod):
![image](https://github.com/primefaces/primevue-nuxt-module/assets/36067662/73381d33-71a3-4fe9-beca-1a4e7f3bf080)
Do you guys have any idea about this? Thank you!

**Comment by mertsincan** [comment]
Interesting! Could you please check <style> order in <head>? The following style should be loaded on top of the tailwind and primevue styles.
```
<style type="text/css" data-primevue-style-id="layer-order">@layer primevue, tailwind-base, tailwind-utilities</style>
```

Exp Output;
```
<head>
    ...
    <style type="text/css" data-primevue-style-id="layer-order">@layer primevue, tailwind-base, tailwind-utilities</style>
    // tailwind or other primevue styles
    ...
</head>
```

**Comment by minhanbkdn** [comment]
`<style type="text/css" data-primevue-style-id="layer-order">@layer tailwind-base, primevue, tailwind-utilities</style>`
The style order same on both env.
I see in the local dev, the CSS for `layer tailwind-base` is loaded after the <style> order setting.
But in prod, it loaded before this <style>.
Any suggestion?

**Comment by mertsincan** [comment]
Hmm! Is there any link to check? Could you also please deploy the following sample project to your server?
https://github.com/primefaces/primevue-examples/tree/main/nuxt-unstyled-tailwind
Does it work for you?

**Comment by minhanbkdn** [comment]
I tried the nuxt styled tailwind, but got the same issue.
I run `yarn build` -> `node .output/server/index.mjs`, but still got the same issue.
https://github.com/primefaces/primevue-examples/blob/main/nuxt-styled-tailwind/nuxt.config.ts

**Comment by mertsincan** [comment]
Thanks a lot for the update! I'll check and get back to you.
