### ISSUE TITLE
Features: `importPT` fields are displayed in the source code

### ISSUE THREAD

**Issue by LemonAppleMo** [primefaces/primevue-nuxt-module#28]
I don't think that field should be in the runtime config. 😂

[https://primevue.org/nuxt/#importpt](https://primevue.org/nuxt/#importpt)

![image](https://github.com/primefaces/primevue-nuxt-module/assets/32638462/f049c306-42ad-4adc-8215-2dc848ba35c2)

**Comment by LemonAppleMo** [comment]
[https://github.com/primefaces/primevue-nuxt-module/blob/main/src/module.ts#L42-L47](https://github.com/primefaces/primevue-nuxt-module/blob/main/src/module.ts#L42-L47)

```js
const { importPT, ...restModuleOptions } = moduleOptions;

nuxt.options.runtimeConfig.public.primevue = {
  ...restModuleOptions,
  ...registered
};
```

I think it's better this way.

**Comment by mertsincan** [comment]
Hi,

This is related to serializable definitions. Please see my comments; 
https://github.com/primefaces/primevue-nuxt-module/issues/6#issuecomment-1772954754

Best Regards,

**Comment by LemonAppleMo** [comment]
I'm so sorry. I've been so busy with the company for the last two months.

Thank you so much for answering my question. 😊😊
