### ISSUE TITLE
how can I import component prop type?

### ISSUE THREAD

**Issue by kimsourly** [primefaces/primevue-nuxt-module#31]
import {} from 'nuxt-primevue';

**Comment by mertsincan** [comment]
Please use;
```
import <Component_Name> from 'primevue/<Component_Name>'
```

**Comment by NerijusD** [comment]
@mertsincan 
how about if I want to import `MenuItem` type? 
tried with:
`import { type MenuItem } from "primevue/menuitem";`

However it failed with message:
`Internal server error: Failed to resolve entry for package "..\src\node_modules\primevue\menuitem". The package may have incorrect main/module/exports specified in its package.json.`
