### ISSUE TITLE
Changing scale on hover doesn't work as expected

### ISSUE THREAD

**Issue by rogrile** [primefaces/primevue-nuxt-module#32]
When using "hover:scale-110" or "hover:scale-125" in an extended  PT configuration with mergeProps and mergeSections set to true, nothing happens when hovering over a button. However, if you add "hover:scale-150" it works without any issues.
If you however add "hover:scale-110" in the extended config, and in the primevue/passthrough/tailwind button configuration, hover will then work as expected.

You can check out it below, where I've added the same config setup and added a scale-125 in assets/presets/grilero/index.js file which extends on the PT tailwind config that primevue comes with:

https://stackblitz.com/edit/nuxt-starter-tfyadx?file=assets%2Fpresets%2Fgrilero%2Findex.js

**Comment by mertsincan** [comment]
Please update config file;
```
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './assets/**/*.{vue,js,ts,jsx,tsx,js}',
    './node_modules/primevue/**/*.{vue,js,ts,jsx,tsx,js}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  darkMode: 'class',
};
```

Best Regards,
