### ISSUE TITLE
Primevue update.

### ISSUE THREAD

**Issue by antlionguard** [primefaces/primevue-nuxt-module#33]
When can we get the new `primevue` update for this package?

And i think this repo should have discussion tab for conversations like this.

**Comment by mertsincan** [comment]
Hello,

This module has `"primevue": "^3.40.1"` dependency. So, you can now use it with the latest version of PrimeVue.

Best Regards,

**Comment by antlionguard** [comment]
> Hello,
> 
> This module has `"primevue": "^3.40.1"` dependency. So, you can now use it with the latest version of PrimeVue.
> 
> Best Regards,

PrimeVue latest version is `3.41.1`. When will this package receive the `3.41.1` update? Or is `3.40.1` available for this package for now? I may have misunderstood something, apologies.

**Comment by mertsincan** [comment]
No no, I may have explained it wrong ;) This module has "primevue": "^3.40.1" dependency. So, the minimum version this module can run on is PrimeVue 3.40.1. You can use it with 3.40.1+. Also it has that **^** sign. When it tries to install the package, the latest PrimeVue version will be installed.

Best Regards,

**Comment by antlionguard** [comment]
I think there's still misunderstanding here :D 

`nuxt-primevue@0.2.1` package still uses `primevue@3.40.1` but i wanna use `primevue@3.41.1`.

I set override inside package.json like this. 

```
  "overrides": {
    "nuxt-primevue": {
      "primevue": "^3.41.1"
    }
  }
```

And now i can use `primevue@3.41.1`. But `0.2.1` version of `nuxt-primevue` still uses `3.40.1` version of `primevue`. [package.json](https://github.com/primefaces/primevue-nuxt-module/blob/main/package.json). 

And i created new pr for this. I hope i did the things right. https://github.com/primefaces/primevue-nuxt-module/pull/34

**Comment by mertsincan** [comment]
Please see; https://michaelsoolee.com/npm-package-tilde-caret/

My test package.json
```
{
  "name": "nuxt-styled-tailwind",
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "6.8.0",
    "nuxt": "^3.7.4",
    "nuxt-primevue": "^0.2.1",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  }
}
```
<img width="1320" alt="Screen Shot 2023-11-27 at 09 41 44" src="https://github.com/primefaces/primevue-nuxt-module/assets/11868120/1cb46aae-5e63-4858-a70d-13a246ba3f8a">

**Comment by antlionguard** [comment]
Very interesting. I also have `nuxt-primevue` set with tilde. Additionally, when I delete the pnpm-lock.yaml file and reinstall it, it still installs the old version. Maybe it's because I installed with `pnpm with --shamefully-hoist`.

**Comment by antlionguard** [comment]
Yep. I tried without --shamefully-hoist pnpm installed new version of `primevue` sorry for interruption :d
