### ISSUE TITLE
It's not possible to change locale settings

### ISSUE THREAD

**Issue by OlePc** [primefaces/primevue-nuxt-module#36]
When using the nuxt module, I don't see any option for setting the locale options specified here [https://primevue.org/configuration/#setlocale](url)

Am I missing something, or is the feature missing from the nuxt module?

**Comment by mertsincan** [comment]
Hi,

Did you try;
```
// nuxt.config.js
primevue: {
   options: {
        locale: {
            accept: 'Aceptar',
            reject: 'Rechazar',
        }
   }
}
```

**Comment by zavvla** [comment]
hi, I'm facing the same problem with Nuxt 3.11.1 with Nitro 2.9.4.
 
`primevue: {
		options: {
			locale: {
				accept: "Aceptar",
				reject: "Rechazar",
			},
		},
	},`

![image](https://github.com/primefaces/primevue-nuxt-module/assets/11782509/f1b1b2b6-36e5-48f6-8e7b-e9c83e33a209)

Could you help me? Maybe I'm writing something wrong, or is there some way to set the global language? Can I have a sample code?
