### ISSUE TITLE
not working InputSwitch component

### ISSUE THREAD

**Issue by Mohammad-Ravand** [primefaces/primevue-nuxt-module#41]
i have project with nuxt3 and installed [primevue ](https://nuxt.com/modules/primevue)with nuxt3 modules, when i want using this component , does not show any thing,
this is my component:
`<template>
    
    <div class="bg-gray-100">
        
        <div class="border z-40 border-blue-400">
            <InputSwitch class="bg-red-400" name="mohammad" v-model="checked" />
        </div>
    </div>

</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
    setup() {
        const checked =ref(false);
        
        return {
            checked
        }
    },
})
</script>
`

**Comment by v-zdorovcev** [comment]
There is no such problem in the sandbox
https://stackblitz.com/edit/nuxt-starter-nzwzhq?file=app.vue

**Comment by mertsincan** [comment]
Yes, I couldn't replicate it. For now, closed. If a new update comes from your side, please reopen this ticket.

Best Regards,
