### ISSUE TITLE
Bad ranking position of primevue in the nuxt modules page

### ISSUE THREAD

**Issue by Dav3rs** [primefaces/primevue-nuxt-module#47]
When listing the UI modules available on the nuxt page, Primevue is buried very deep down. Even when sorting by downloads, it is not on the first results. This can be improved by using the metrics from the main package instead of this one, maybe the nuxt integration can be shipped on the main primevue package and deprecate nuxt-primevue.

![imagen](https://github.com/primefaces/primevue-nuxt-module/assets/50024128/04ea1d77-42ae-4007-bbe0-6edaf2474696)

![imagen](https://github.com/primefaces/primevue-nuxt-module/assets/50024128/98f460ae-b916-4a0a-b67b-bcd182c76da3)

**Comment by mertsincan** [comment]
Yes, you're right! We're keeping it as a separate package for now. We are considering moving it into primevue after the 4+ version. Thanks a lot for your report!
