### ISSUE TITLE
Nuxt won't import the new components

### ISSUE THREAD

**Issue by nicolaspda** [primefaces/primevue-nuxt-module#48]
After the update to 3.48.0 (PrimeVue) i was expecting to use the new components "IconField" and "InputIcon", but was not able to.

**What i did:**
1-npm update primevue --save
2-npm install
3-npm run dev

**The result:**
![image](https://github.com/primefaces/primevue-nuxt-module/assets/48483430/ce938dbe-52a9-4700-ac0c-539409db28f9)

**Comment by Yves852** [comment]
Have you tried to use `nuxi upgrade --force` similarly to a Nuxt update to ensure all sub dependencies are updated?

**Comment by mertsincan** [comment]
Hi all,

Thanks a lot for your report! I'll release the new version today.
