### ISSUE TITLE
Ability to pin primevue version with shamefully-hoist

### ISSUE THREAD

**Issue by Yves852** [primefaces/primevue-nuxt-module#49]
How can I pin primevue version in the context of a Nuxt project that requires (.npmrc) `shamefully-hoist=true`? 

Recently some components we use are broken but I can't manage to rollback to a previous version of  primevue (either for testing or temporary solution) as nuxt-primevue  "^0.2.2" fetch automatically the last version.

### Tried solution

Adding ovverides in package.json,  this had no effects. Tried to delete `pnpm-lock.yaml` then run `pnpm i` but no changes aswell.
```json
"overrides": {
    "nuxt-primevue": {
      "primevue": "3.47.2"
    }
  },
```

The resulting pnpm-lock.yaml

```yaml
  /nuxt-primevue@0.2.2(rollup@4.9.6):
    resolution: {integrity: sha512-OfXDe5V0WovXt9b2GOjYV1kyVXmcFfj+6DqVs1pbeP4EyF2H0SbIMoUTT8Ax+sXT/tQ+mXr3qTFD9Y6IL+Y9og==}
    dependencies:
      '@nuxt/kit': 3.10.1(rollup@4.9.6)
      primevue: 3.48.1
    transitivePeerDependencies:
      - rollup
      - supports-color
      - vue
    dev: true
```

### Versions:
node: v20.10.0
pnpm: v8.15.1
nuxt: v3.10.1
nuxt-primevue: v0.2.2

Related: https://github.com/primefaces/primevue-nuxt-module/issues/33

Thanks

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! I'll release the new version today. Please try it. If the problem persists, please reopen this ticket.

Best Regards,

**Comment by Yves852** [comment]
> Hi,
> 
> Thanks a lot for your report! I'll release the new version today. Please try it. If the problem persists, please reopen this ticket.
> 
> Best Regards,

I'm not a collaborator on this repository, I don't have the button to reopen my ticket. 

For my problem with the component I managed to fix, it was on our side.

About `primevue` version unfortunately I couldn't manage to pin it with `nuxt-primevue 0.3.0`, that problem persist. Maybe I should open a new ticket as a feature request instead? My ticket is a little confusing on its topic, my apologies.
