### ISSUE TITLE
[Question] How to enable tree shaking of components ?

### ISSUE THREAD

**Issue by geminigeek** [primefaces/primevue-nuxt-module#56]
hi,
currently all components are loaded in final build, how can we build only what we are using ?

**Comment by shtse8** [comment]
I have the same question and am wondering if we need to configure unplugin for primevue manually.

**Comment by dencs08** [comment]
Right now i exclude loading unused components via options like so:

It would be nice to have something which would automate it though.

`    components: {
        exclude: ['Galleria', 'TreeTable', 'PickList'],
    },
    composables: {
    },
    directives: {
        exclude: ['Ripple']
    },
};`

**Comment by geminigeek** [comment]
its better if its implemented with vite unplugin, the resolver is already there https://github.com/unplugin/unplugin-vue-components/blob/main/src/core/resolvers/prime-vue.ts , this way we don't have to make all components global, i have no idea how vite works but seems a good option

**Comment by Yves852** [comment]
Are you looking for this ? It's manual treeshaking but already better than no treeshaking: https://primevue.org/nuxt/#components

```ts
// nuxt.config.ts
primevue: {
    components: {
        include: ['Button', 'DataTable']
    }
}

```

**Comment by kylevdr** [comment]
You need to add
```
primevue: {
  components: {
    include: [],
  }
}
```
to nuxt.config.js.

From there, you can either add the components you need to your config as @Yves852 demonstrated, or you can import them directly where you use them (no nuxt auto-import).

**Comment by mertsincan** [comment]
Hello,
I added `autoImport: true | false(default)` to new `@primevue/nuxt-module` plugin. Please see;
https://github.com/primefaces/primevue/issues/5935

Best Regards,
