### ISSUE TITLE
Accordion: list inside accordion causes content to be duplicated (only in primevue-nuxt)

### ISSUE THREAD

**Issue by luizzappa** [primefaces/primevue-nuxt-module#57]
If you include a list within an Accordion, its contents are duplicated. 

This error only happens with `primevue-nuxt`, I was unable to reproduce the same problem with `primevue` only.

**Reproducer**: https://stackblitz.com/edit/primevue-nuxt-issue-template-7scwyq?file=app.vue

```javascript
    <Accordion>
      <AccordionTab>
        <template #header>
          <span class="font-semibold lg:font-bold text-base lg:text-lg">1. Introduction</span>
        </template>
        <p class="m-0 text-base lg:text-lg font-extralight">
            MY LIST
            <ul>
              <li>Item 1</li>
              <li>Item 2</li>
              <li>Item 3</li>
           </ul>
           Lalalla
        </p>
      </AccordionTab>
    </Accordion>
```

![image](https://github.com/primefaces/primevue-nuxt-module/assets/65685842/5e0b0360-ce2b-4e8d-8d75-961ac41850cc)

**Comment by mertsincan** [comment]
Interesting! I'll check it and get back to you.

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate it. Could you please try the new `@primevue/nuxt-module` package?
