### ISSUE TITLE
importPT removing backslashes of path on Windows

### ISSUE THREAD

**Issue by noahhorlacher** [primefaces/primevue-nuxt-module#58]
This is my nuxt.config.ts:

```
import path from 'path'

export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "nuxt-primevue"
  ],
  primevue: {
    importPT: { from: path.resolve(__dirname, './presets/wind/')},
  }
})
```

**I'm using nuxt 3.10.3, primevue 3.49.1 and nuxt-primevue 0.3.1**

Nuxt throws the following error:
`Pre-transform error: Failed to resolve import "C:UsersMyUsernameDesktopGithubTestApppresetswind`

This fixes it:
import path from 'path'

export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    "nuxt-primevue"
  ],
  primevue: {
    importPT: { from: path.resolve(__dirname, './presets/wind/').replaceAll('\\', '/')},
  }
})

Consider updating the primevue plugin

Thank you

**Comment by Lehoczky** [comment]
Fixed by: https://github.com/primefaces/primevue-nuxt-module/pull/53

**Comment by Lehoczky** [comment]
@mertsincan could you please take a look at the linked PR? This is a very easily encountered bug by Windows users, and my fix is pretty simple.

**Comment by fazrisuhada007** [comment]
thanks bro, its work for me
