### ISSUE TITLE
Password component nested passthrough attributes not working

### ISSUE THREAD

**Issue by trombonist76** [primefaces/primevue-nuxt-module#62]
Hello! I am using Password component but nested passthrough attributes not effects InputText component inside Password component.

`<p-password v-model="inputValue" :pt="{ input: { class: 'w-full' } }" w-full/>`

![Screenshot 2024-04-06 at 01 22 33](https://github.com/primefaces/primevue-nuxt-module/assets/66271151/bb9e07ec-3a19-4a8d-99b3-d36e02f1f942)

**Comment by mertsincan** [comment]
Hi,

I think this is not related to primevue-nuxt-module. Could you please create a new ticket in primevue core github?

Best Regards,
