### ISSUE TITLE
It is not using the lastest version v4 PrimeVue 

### ISSUE THREAD

**Issue by alcidesrh** [primefaces/primevue-nuxt-module#65]
Basically what the title says.  Module install version 3 setup. Maybe version 4 of PrimeVue has not been released yet. However according to https://v4.primevue.org/ it is already available. Thanks in advance.

**Comment by edimitchel** [comment]
I'm adding my 2cts: several times you (mainteners) annonces a new version for getting the compatibility of primevue 4 with this nuxt module.

Please, could we have an official update about that missing piece?

**Comment by edimitchel** [comment]
Some news
https://twitter.com/cagataycivici/status/1790022285782393299?t=vqdg96rLWzZk05yOEChccQ&s=19

**Comment by roobr** [comment]
Any update on compatibility with V4?

**Comment by edimitchel** [comment]
We have to wait for the version v4.RC1

**Comment by mertsincan** [comment]
Yes, I have completed my work on v4. Now I started preparing the version of this module that is compatible with PrimeVue 4. It will be ready with RC1.

**Comment by adrianBasave** [comment]
If you follow the nuxt 3 config docs in PrimeVue 4, you get this result. According to the documentation, you should get the second image. I've tried all that comes to mind. I still get an unstyled version. I don't understand how you're loading the styles even when explicitly importing Aura (or any other theme) as a plugin.

<img width="520" alt="image" src="https://github.com/primefaces/primevue-nuxt-module/assets/85233867/4df231bb-1737-4c5e-96cd-78feb4612690">

<img width="808" alt="image" src="https://github.com/primefaces/primevue-nuxt-module/assets/85233867/a2fdcd6f-d8f8-4db8-8e34-d97da9872da9">

**Comment by AndyLukac** [comment]
I was having the same issue but now with rc2 I am getting errors. https://github.com/primefaces/primevue-nuxt-module/issues/71
