### ISSUE TITLE
V4.0.0-beta.4 and primevue v4.0.0-beta.4 styled mode: Unable to Import theme.

### ISSUE THREAD

**Issue by patriciorivera** [primefaces/primevue-nuxt-module#68]
According docs: [https://v4.primevue.org/nuxt/#importtheme](https://v4.primevue.org/nuxt/#importtheme)

[https://stackblitz.com/edit/nuxt-starter-tzwy7w?file=nuxt.config.ts](https://stackblitz.com/edit/nuxt-starter-tzwy7w?file=nuxt.config.ts)

[worker reload] [worker init] Directory import '/home/projects/nuxt-starter-tzwy7w/node_modules/primevue/themes' is not supported resolving ES modules imported from /home/projects/nuxt-starter-tzwy7w/theme.js
Did you mean to import primevue/themes/index.mjs?

**Comment by ljcremer** [comment]
I am having the same issues with imparting a theme

**Comment by AndyLukac** [comment]
Also having the same issue.

**Comment by mertsincan** [comment]
Please install and use `@primevue/themes`;
https://stackblitz.com/edit/nuxt-starter-jqwq9r?file=package.json,theme.js,nuxt.config.ts

Best Regards,

**Comment by xarthurx** [comment]
> Please install and use `@primevue/themes`; https://stackblitz.com/edit/nuxt-starter-jqwq9r?file=package.json,theme.js,nuxt.config.ts
> 
> Best Regards,

Please add it to the documentation. :)
