### ISSUE TITLE
[nuxt] Could not access `pt`. The only available runtime config keys on the client side are `public` and `app`

### ISSUE THREAD

**Issue by Tarabass** [primefaces/primevue-nuxt-module#69]
After a clean installation I get the following warning in the console. In bigger projects it can even result in an error instead of a warning. 

`[nuxt] Could not access 'pt'. The only available runtime config keys on the client side are 'public' and 'app'. See 'https://nuxt.com/docs/guide/going-further/runtime-config' for more information.`

https://stackblitz.com/edit/github-ydzyjt

```npm
npx nuxi init NuxtPrimeVueTest
npx nuxi@latest module add primevue
```

**Comment by borsTiHD** [comment]
I have the same problem.
I am trying to update an project to the latest dependencies.  

Among others `nuxt: v3.12.1` and Primevue with `@primevue/nuxt-module: v4.0.0-rc.1`

**Comment by petter-tchirkov** [comment]
Same issue here, fresh installation

**Comment by kambanwait** [comment]
Same issue here, just replicated it with the latest PrimeVue 'RC' and Nuxt version. Also happens with PrimeVue3 latest and latest Nuxt 😭:

https://stackblitz.com/edit/nuxt-starter-vxuc17?file=app.vue

**Comment by petter-tchirkov** [comment]
can anyone tell the latest working version?

**Comment by Ice-Hazymoon** [comment]
same issue.

**Comment by Tarabass** [comment]
Discussion in Nuxt; https://github.com/nuxt/nuxt/discussions/27645

**Comment by Tarabass** [comment]
> can anyone tell the latest working version?

Downgrade nuxt to [3.11.2](https://www.npmjs.com/package/nuxt/v/3.11.2) will suppress the logging. Due to changes [within Nuxt](https://github.com/nuxt/nuxt/commit/601a2620b89220679592230a237f7ef13fdeabf9) this warning is getting logged now, while the problem may have existed for a longer time.

**Comment by mertsincan** [comment]
Fixed in core. Thanks a lot for your reports!
